packages:
  - 'packages/*'

catalogs:
  dev:
    'bumpp': ^10.1.1
    '@changesets/cli': ^2.27.11
    '@eslint/js': ^9.15.0
    '@stylistic/eslint-plugin': ^2.12.1
    '@tsconfig/node22': ^22.0.2
    '@types/node': ^22.17.2
    '@vue/eslint-config-typescript': ^14.6.0
    'eslint': ^9.15.0
    'eslint-flat-config-utils': ^2.1.1
    'eslint-plugin-vue': ~9.33.0
    'husky': ^9.1.7
    'lint-staged': ^16.1.6
    'tsdown': ^0.15.0
    'typescript': ~5.8.3
    'typescript-eslint': ^8.16.0

ignoredBuiltDependencies:
  - rolldown

onlyBuiltDependencies:
  - esbuild
