packages:
  - 'packages/*'

catalogs:
  dev:
    '@changesets/cli': ^2.27.11
    'radash': ^12.1.1

    'eslint': ^9.15.0
    '@eslint/js': ^9.15.0
    '@stylistic/eslint-plugin': ^2.12.1
    '@vue/eslint-config-typescript': ^14.6.0
    'eslint-flat-config-utils': ^2.1.1
    'eslint-plugin-vue': ~9.33.0
    'typescript-eslint': ^8.16.0

    'unplugin-auto-import': ^20.1.0
    'unplugin-icons': ^22.2.0
    'unplugin-vue-components': ^29.0.0

    '@tsconfig/node22': ^22.0.2
    '@types/node': ^22.17.2

    'husky': ^9.1.7
    'lint-staged': ^16.1.6

    'typescript': ~5.8.3
    'tsdown': ^0.15.0
    'vite': ^7.1.3

ignoredBuiltDependencies:
  - rolldown

onlyBuiltDependencies:
  - esbuild
